apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spring-academy.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "spring-academy.selectorLabels" . | nindent 6 }}
