name: Jekyll site CI
on:
  push:
    branches: 
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Autotagger
      id: autotagger
      uses: ButlerLogic/action-autotag@1.0.2
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Build
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build"
        
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ctsc/spring.academy:${{ steps.autotagger.outputs.tagname }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
